# Generated by Django 5.0.6 on 2024-06-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_chatmessage_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='exam',
        ),
    ]
