# Generated by Django 5.0.6 on 2024-05-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Objective', 'Objective'), ('Subjective', 'Subjective')], default='Subjective', max_length=20),
            preserve_default=False,
        ),
    ]
