# Generated by Django 5.0.6 on 2024-06-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
