# Generated by Django 5.0.6 on 2024-06-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Home.exam'),
            preserve_default=False,
        ),
    ]
