# Generated by Django 5.0.6 on 2024-06-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
