# Generated by Django 5.0.6 on 2024-06-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_proctoremail_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Duration in minutes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
