# Generated by Django 5.0.6 on 2024-06-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_exam_duration_alter_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
    ]
