# Generated by Django 5.2.1 on 2025-07-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='email_list',
            field=models.TextField(blank=True, help_text='Comma-separated list of emails (for bulk assign)'),
        ),
    ]
