# Generated by Django 5.2.1 on 2025-07-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_exam_email_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='email_list',
        ),
    ]
